gcp:
  project: your-gcp-project-id
  region: your-region
  job_name: your-job-name
  staging_location: gs://your-bucket/staging
  temp_location: gs://your-bucket/temp
  runner: DataflowRunner

sensors:
  sensor1:
    table: table1
  sensor2:
    table: table2

mysql:
  instance_connection_name: your-project:your-region:your-instance
  user: your-username
  password: your-password
  database: your-database
