gcp:
  project: gcp-project-id
  region: region
  job_name: sensor-data-pipeline
  staging_location: gs:// bucket/staging
  temp_location: gs:// bucket/temp
  runner: DataflowRunner  

pubsub:
  topics:
    - projects/project-id/topics/topic1
    - projects/project-id/topics/topic2

sensors:
  sensor1:
    table: sensor_readings_table1
    type: temperature
  sensor2:
    table: sensor_readings_table2
    type: humidity

transforms:
  validation:
    required_fields:
      - sensor_id
      - value
      - timestamp

sinks:
  bigquery:
    enabled: false
    dataset: dataset
    table: table
  cloud_storage:
    enabled: false
    bucket: bucket
    path: path
  sql:
    enabled: true
    instance_connection_name: project:region:instance
    project: gcp-project-id
    region: region
    instance: instance
    user: username
    password: password
    database: database
    table_prefix: sensor_data_
