# config.yaml
credentials:
  # keep format like this to connect to database
  #host (str): Host adres of the database, found on the GCP console (go to the desired database instance)
  #user (str): the user that tries to connect to the database (in testing probably a name, 
  #   could be other instances from the car as well —> see GCP console/Database/Users)
  #password (str): user password (set in GCP, see console). Password will be hashed and hash will be used
  #database (str): the name of the MySQL database that you’re trying to connect to.
  #See GCP console and consult your team lead for which database you should connect to
  host      : 127.0.0.1
  user      : root
  password  : Roarlol12
  database  : hydro_db
  port      : 3306

csv_files:
  location: CSV_files/database

sql_files:
  location: sql_files/
  insert_sripts:
    users: insert_users
    sensors: insert_sensor_data
    endpoints: insert_reading_endpoint
    events: insert_events
    drivers: insert_drivers
    components: insert_car_components
  table_creation: #order is important ! 
    users: create_users
    drivers: create_drivers
    components: create_car_components
    endpoints: create_reading_end_point
    events: create_events
  sensor_data:
    identifier: sensor_ #in beginning of name
    entity: sensor_entity


fetch_data:
  drivers:
    url       : https://ergast.com/api/f1/2023/drivers.json
    filename  : drivers.csv
    json_path : ["MRData", "DriverTable", "Drivers"]
  events:
    url       : https://ergast.com/api/f1/2023.json
    filename  : events.csv
    json_path : ["MRData", "RaceTable", "Races"]
